# Generated by Django 2.2 on 2020-03-23 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_of_dep', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats', models.PositiveSmallIntegerField()),
                ('from_location', models.CharField(choices=[('IGI', 'DELHI AIRPORT'), ('PIL', 'PILANI'), ('LOH', 'LOHARU'), ('NDL', 'New Delhi Railway Station'), ('JAI', 'Jaipur Airport')], max_length=3)),
                ('to_location', models.CharField(choices=[('IGI', 'DELHI AIRPORT'), ('PIL', 'PILANI'), ('LOH', 'LOHARU'), ('NDL', 'New Delhi Railway Station'), ('JAI', 'Jaipur Airport')], max_length=3)),
                ('starting_time', models.TimeField()),
                ('date', models.DateField()),
                ('cab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='main.Cab')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
